source 'http://rubygems.org'

gem 'rails', '3.0.1'
gem 'haml'
gem 'compass', '>= 0.10.5'
gem 'RedCloth'
gem 'hpricot'
gem 'paperclip'
gem 'prarupa'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'mysql'
